# Usa a imagem oficial do NGINX como base
FROM nginx:alpine

# Remove a configuração padrão do NGINX
RUN rm /etc/nginx/conf.d/default.conf

# Copia o arquivo de configuração personalizado para o container
COPY default.conf /etc/nginx/conf.d